<?php

namespace AppBundle\Repository;

/**
 * JourFerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourFerieRepository extends \Doctrine\ORM\EntityRepository {

    public function nbrJoursFeries(string $dateDebut, string $dateFin) {

        $connection = $this->getEntityManager()->getConnection();

        $sth = $connection->prepare("CALL NombreJours('" . $dateDebut . "','" . $dateFin . "');");
        $sth->execute();
        $nbr = $sth->fetch();

        return $nbr['NombreJours'];
    }

}
