<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository {

    public function findNotesByEtudiantId($idEtudiant) {

        $em = $this->getEntityManager();

        return $em->createQuery(
                                "SELECT n FROM AppBundle:Note n WHERE n.etudiant =".$idEtudiant
                        )
                        ->getResult();
    }

}
